"""
Log analyzer for GitHub push issues and automated fixes.
"""

import re
from pathlib import Path
from typing import Dict, List


def parse_git_errors(log_content: str) -> List[str]:
    """Parse Git error messages from log content."""
    error_patterns = [
        r"fatal: repository '.*' not found",
        r"Permission denied.*",
        r"Authentication failed.*",
        r"remote: Repository not found",
        r"fatal: unable to access.*",
    ]

    errors = []
    for pattern in error_patterns:
        matches = re.findall(pattern, log_content, re.IGNORECASE)
        errors.extend(matches)

    return errors


def generate_fix_commands(errors: List[str]) -> List[str]:
    """Generate fix commands based on detected errors."""
    commands = []

    for error in errors:
        if "repository not found" in error.lower():
            commands.append("# Create repository on GitHub: https://github.com/new")
            commands.append(
                "git remote set-url origin https://github.com/Maggot4703/Crew.git"
            )

        elif "authentication failed" in error.lower():
            commands.append(
                "# Use Personal Access Token: https://github.com/settings/tokens"
            )
            commands.append("git config --global user.name 'Maggot4703'")

        elif "permission denied" in error.lower():
            commands.append("# Check repository ownership and SSH keys")

    return list(set(commands))  # Remove duplicates


def create_fix_script() -> None:
    """Create an executable fix script."""
    script_content = """#!/bin/bash
# Automated GitHub Push Fix Script
# Generated by NPCs Data Processing Tool

echo "🔧 Fixing GitHub push issues..."

# Fix remote URL
git remote set-url origin https://github.com/Maggot4703/Crew.git

# Set correct user
git config user.name "Maggot4703"
git config user.email "maggot4703@example.com"

# Stage and commit
git add .
git commit -m "Fix GitHub push issues and update repository"

# Push to GitHub
echo "📤 Attempting push..."
git push -u origin main

echo "✅ Fix script completed"
"""

    with open("fix_github.sh", "w") as f:
        f.write(script_content)

    # Make executable
    import os

    os.chmod("fix_github.sh", 0o755)

    print("📜 Created executable fix script: fix_github.sh")
